Option for fast font render (as opposed to blended)
Bill-Gray/PDCursesMod pull request #180
Opened 2020-09-03 01:53 UTC by jaybill

The SDL2 version uses the 'Blended' version of the renderer, making it impossible to have pixel perfect fonts. I added a variable called `pdc_font_render_fast` which, if set, uses the 'solid' renderer, which is faster, but pixel accurate with no blending.

2020-09-03 10:03 UTC, GitMensch requested changes
The changes itself are fine, from my side the only missing thing is the documentation part (in the port doc to document the option + ChangeDoc for one-time information), please add this.

2020-09-03 18:59 UTC, jaybill commented
> Just for reference: [SDL: Render modes](http://www.libsdl.org/projects/SDL_ttf/docs/SDL_ttf_42.html#SEC42).

I wonder if I should rework it so that you could select the render mode from those three? An int with an enum?

2020-09-03 19:07 UTC, GitMensch commented
> I wonder if I should rework it so that you could select the render mode from those three?

Yes, providing an option to switch using the same names would be useful.
As the docs for all ports say "either include the header or define as needed" it seems an externalized int would be good, using `#define`d values in the header (1 to 3 with the same names).

2020-09-03 19:10 UTC, GitMensch reviewed
docs are fine, but the name and value should be adjusted to care for all three modes

2020-09-04 20:56 UTC, jaybill commented
I've updated this PR to allow selecting one of the ttf render modes, but selecting the one that was already being used (blended) by default.

2020-09-05 15:07 UTC, GitMensch approved these changes

2020-09-05 15:15 UTC, GitMensch commented
Looks ready for merge (if possible, please add a note that fro SDL1/SDL2 ports may use an adjusted font rendering now by changing `pdc_sdl_render_mode` in https://github.com/Bill-Gray/PDCursesMod/blob/master/docs/HISTORY.md.

@Bill-Gray: Do you see any issues with merging this to master? If not I'll trigger the merge next week. [side-notes: the appveyor integration is still missing, so it isn't build for the PR (and therefore we don't have any sdl port actually build automated...); the OW-windows builds fail since your last change because of missing header).

2020-09-05 19:44 UTC, merged

2020-09-05 20:24 UTC, Bill-Gray commented
@jaybill @GitMensch Thanks for this;  looks good to me.

As an experiment,  I added the following lines to `sdltest.c`:
```
    if( argc > 1)
    {
         extern int pdc_sdl_render_mode;

         pdc_sdl_render_mode = atoi( argv[1]);
    }
```
...enabling me to run `./sdltest 1`, `./sdltest 2`, `./sdltest 3` to see the effect of each mode.  The difference between 1 ("solid" mode) and the other two modes was quite obvious.  The "blended" mode may be useful if the SDLx platform gains the concept of a default background;  you could draw your surface,  then have text appear that leaves the background intact.  But that's a long way off.

Simon,  the automated builds/OpenWATCOM issue involves CMake,  which is not something I know much about.  The "traditional" makefiles have been <a href="https://github.com/Bill-Gray/PDCursesMod/commit/34a9d9efd250c7d236ad70789c5570cfa822edd6"> modified to include `winmm.lib`</a>. At a casual glance,  it appears to me as if `cmake/project_common.cmake` needs these two lines added,  just before `elseif(APPLE)`:
```
elseif(WIN32 AND WATCOM)
    set(EXTRA_LIBS winmm.lib)
```
If that looks reasonable,  I'll add/commit/push those two lines and we'll see what happens.

2020-09-07 18:49 UTC, GitMensch commented
> If that looks reasonable, I'll add/commit/push those two lines and we'll see what happens.

That looks reasonable to me, I've did nearly the same and placed it in #181 to let Travis show if that helped (or possibly had broken even more ;-)